config/routes.rb
ProjectCalendar::Application.routes.draw do
  resources :projects

  devise_for :users
  scope "/admin" do
    resources :users
  end

  resources :events

  get "calendar/index"
  get "calendar/show"

  get "reports/index"
  get "reports/:user_id", to: 'reports#get', as: 'reports_get'

  root 'calendar#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true

  has_many :events, inverse_of: :user, :dependent => :delete_all

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  def self.search(search)
    if search
      where('name LIKE ? or email LIKE ?', "%#{search}%", "%#{search}%")
    else
      scoped
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_admin
  handles_sortable_columns

  def index
    @users = User.search(params[:search]).order(sortable_column_order).paginate(:per_page => 50, :page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(:controller => 'users', :action => 'index') }
    end
  end

  def edit
    @user = User.find(params[:id])
  end

def update
  @user = User.find(params[:id])
  if @user.update_attributes(user_params)
    flash[:success] = "Profile updated."
    respond_to do |format|
      format.html { redirect_to(:controller => 'users', :action => 'index') }
    end
  else
    render 'edit'
  end
end

private
  def user_params
    params.require(:user).permit(:name, :email, :admin)
  end

  def require_admin
    unless current_user && current_user.admin?
          flash[:error] = "Unauthorised user"
          redirect_to root_path
        end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def not_this_user?(user)
    if user.id != current_user.id
      true
    else
      false
    end
  end
end

app/views/users/edit.html.erb
<h2>Edit <%= @user.name %></h2>

<%= form_for @user do |f| %>

  <div class="field">
    <%= f.label :name %>
    <br />
  <%= f.text_field :name %>
</div>

  <div class="field">
    <%= f.label :email %>
    <br />
  <%= f.email_field :email %>
</div>

<% if current_user.admin? %>
<div class="field">
  <%= f.label :admin %>
  <br />
  <%= f.check_box :admin %>
</div>
<% end %>

  <div>
    <%= f.submit "Update", class: 'btn btn-default' %>
  </div>
<% end %>

<%= link_to "Back", :back %>

app/views/users/index.html.erb
<h1>Users</h1>

<div class="col-md-4 col-md-offset-8">
<%= form_tag users_path, :method => 'get' , class: 'form-inline' do %>
    <%= text_field_tag :search, params[:search], class: 'input-small', placeholder: 'name or email' %>
    <%= submit_tag "Search", :name => nil, class: 'btn btn-default' %>
<% end %>
</br>
</div>

<table class="table">
  <tr>
    <th><%= sortable_column "Name" %></th>
    <th><%= sortable_column "Email" %></th>
    <th><%= sortable_column "Admin" %></th>
    <th>Calendar</th>
    <th>Report</th>
    <th>Actions</th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.admin? ? 'yes' : 'no' %></td>
    <td><%= link_to 'Calendar', calendar_show_path(:user => user.id) %></td>
    <td><%= link_to 'Report', reports_get_path(user) %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td>
      <%= link_to_if not_this_user?(user), "Delete", {:controller => "users", :action => 'destroy', :id => user.id}, data: { confirm: "Are you sure you want to delete #{user.name}?" } , :method => :delete %>
    </td>
  </tr>
<% end %>
</table>

<%= will_paginate @products %>

app/views/users/report.html.erb
<h2>Report : <%= @user.name %></h2>

<table class="table">
  <tr>
    <th>Title</th>
    <th>Start</th>
    <th>End</th>
    <th>Description</th>
  </tr>

<% @user.events.each do |event| %>
  <tr>
    <td><%= event.title %></td>
    <td><%= event.starts_at %></td>
    <td><%= event.ends_at %></td>
    <td><%= event.description %></td>
  </tr>
<% end %>
</table>