config/routes.rb
ProjectCalendar::Application.routes.draw do
  resources :projects

  devise_for :users
  scope "/admin" do
    resources :users
  end

  resources :events

  get "calendar/index"
  get "calendar/show"

  get "reports/index"
  get "reports/:user_id", to: 'reports#get', as: 'reports_get'

  root 'calendar#index'
end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :title, :total_hours, presence: true
  validates :total_hours, numericality: {only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 24}

  belongs_to :user, inverse_of: :events
  belongs_to :project, inverse_of: :events

  def set_hours(start_time, end_time)
    self.starts_at = start_time
    self.ends_at = end_time

    self.starts_at = self.starts_at.change(hour: 8)
    self.ends_at = self.ends_at.change(hour: 16)
  end

  def as_json(options = {})
    {
      :id => self.id,
      :title => self.title,
      :description => self.description || "",
      :start => starts_at.rfc822,
      :end => ends_at.rfc822,
      :allDay => self.all_day,
      :color => self.color,
      :recurring => false,
      :url => Rails.application.routes.url_helpers.event_path(id)
    }
  end

  def self.format_date(date_time)
    Time.at(date_time.to_i).to_formatted_s(:db)
  end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      columns = ['Title', 'Date', 'Hours', 'Project', 'Starting Time', 'Ending Time', 'Description']
      csv << columns
      all.each do |event|
        csv << [event.title, event.starts_at.to_date, event.total_hours, event.project.name, event.starts_at.strftime("%H:%M"), event.ends_at.strftime("%H:%M"), event.description]
      end
    end
  end

  def days_span
    Date.parse(self.starts_at.to_s)..Date.parse(self.ends_at.to_s)
  end

  def multiple_days?
    self.days_span.count > 1 ? true : false
  end

  def self.search(search)
    if search
      project_id = Project.where(name: search)
      where('title LIKE ? or project_id LIKE ?', "%#{search}%", project_id)
    else
      scoped
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.xml
  def index
    events_for_user!

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @events }
      format.js  { render :json => @events }
    end
  end

  # GET /events/1
  # GET /events/1.xml
  def show
    @event = Event.find(params[:id])

    if @event.user.id != current_user.id && !current_user.admin?
      flash[:error] = "Unauthorised access"
      redirect_to root_path
    else
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @event }
        format.js { render :json => @event.to_json }
      end
    end
  end

  # GET /events/new
  # GET /events/new.xml
  def new
    @event = Event.new
    @event.set_hours(params[:start], params[:end])

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])

    if @event.user.id != current_user.id && !current_user.admin?
      flash[:error] = "Unauthorised access"
      redirect_to root_path
    end
  end

  # POST /events
  # POST /events.xml
  def create
    @events = []

    @event = Event.new(event_params)
    @event.user_id = current_user_id

    if @event.multiple_days?
      @event.days_span.each do |day|
        @new_event = Event.new(event_params)
        @new_event.starts_at = @new_event.starts_at.change(day: day.day, month: day.month, year: day.year)
        @new_event.ends_at = @new_event.ends_at.change(day: day.day, month: day.month, year: day.year)
        @new_event.user_id = current_user_id

        @events << @new_event
      end
    else
      @events << @event
    end

    Event.transaction do
      @events.each(&:save!)
    end

    respond_to do |format|
      format.html { redirect_to(calendar_index_path, :notice => 'Event was successfully created.') }
      format.xml  { render :xml => @event, :status => :created, :location => @event }
    end

  rescue
    respond_to do |format|
      format.html { render :action => "new" }
      format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
    end

  end

  # PUT /events/1
  # PUT /events/1.xml
  # PUT /events/1.js
  # when we drag an event on the calendar (from day to day on the month view, or stretching
  # it on the week or day view), this method will be called to update the values.
  # viv la REST!
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(event_params)
        format.html { redirect_to(@event, :notice => 'Event was successfully updated.') }
        format.xml  { head :ok }
        format.js { head :ok}
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
        format.js  { render :js => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.xml
  def destroy
    @event = Event.find(params[:id])

    if @event.user.id != current_user.id && !current_user.admin?
      flash[:error] = "Unauthorised access"
      redirect_to root_path
    else
      @event.destroy
    end

    respond_to do |format|
      format.html { redirect_to(:controller => 'calendar', :action => 'index') }
      format.xml  { head :ok }
    end
  end

private
    def event_params
      params.require(:event).permit(:title, :starts_at, :ends_at, :all_day, :description, :color, :total_hours, :project_id)
    end

    def events_for_user!
      if session[:selected_user_id]!= nil && current_user.admin?
        @events = User.where(id: session[:selected_user_id]).first.events
      else
         @events = current_user.events
      end
    end

    def current_user_id
      if session[:selected_user_id] != nil && current_user.admin?
        session[:selected_user_id]
      else
         current_user.id
      end
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>

  <%= render 'layouts/errors', object: @event %>

  <div class="form-group">
    <%= f.label :title %><br />
    <%= f.text_field :title, autofocus: true %>
  </div>
  <div class="form-group">
    <%= f.label :starts_at %><br />
    <%= f.datetime_select :starts_at %>
  </div>
  <div class="form-group">
    <%= f.label :ends_at %><br />
    <%= f.datetime_select :ends_at %>
  </div>
    <div class="form-group">
    <%= f.label :total_hours %><br />
    <%= f.text_field :total_hours %>
  </div>
  <div class="form-group">
    <%= f.label :all_day %><br />
    <%= f.check_box :all_day %>
  </div>
    <div class="form-group">
    <%= f.label :project %><br />
    <%= collection_select(:event, :project_id, Project.where(finished: false), :id, :name) %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
    <div class="form-group">
    <%= f.label :color %><br />
    <%= f.select :color, options_for_select([["yellow", "yellow"], ["blue", "blue"], ["red", "red"], ["green", "green"]]) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', calendar_index_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Starts at</th>
    <th>Ends at</th>
    <th>All day</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.title %></td>
    <td><%= event.starts_at %></td>
    <td><%= event.ends_at %></td>
    <td><%= event.all_day %></td>
    <td><%= event.description %></td>
    <td><%= link_to 'Show', event %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />
<%= link_to 'view calendar', calendar_index_path %>
<br/>
<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', calendar_index_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @event.title %>
</p>

<p>
  <b>Starts at:</b>
  <%= @event.starts_at %>
</p>

<p>
  <b>Ends at:</b>
  <%= @event.ends_at %>
</p>

<p>
  <b>Total hours:</b>
  <%= @event.total_hours %>h
</p>

<p>
  <b>All day:</b>
  <%= @event.all_day %>
</p>

<p>
  <b>Project:</b>
  <%= @event.project.name %>
</p>

<p>
  <b>Description:</b>
  <%= @event.description %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Destroy', @event, :confirm => 'Are you sure?', :method => :delete %> |
<%= link_to 'Back', calendar_index_path %>