config/routes.rb
ProjectCalendar::Application.routes.draw do
  resources :projects

  devise_for :users
  scope "/admin" do
    resources :users
  end

  resources :events

  get "calendar/index"
  get "calendar/show"

  get "reports/index"
  get "reports/:user_id", to: 'reports#get', as: 'reports_get'

  root 'calendar#index'
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :events, inverse_of: :project, :dependent => :delete_all
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :require_admin, :set_project, only: [:show, :edit, :update, :destroy]
  handles_sortable_columns

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.order(sortable_column_order).paginate(:per_page => 50, :page => params[:page])
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path, notice: 'Project was successfully created.' }
        format.json { render action: 'index', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to projects_path, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :finished, :started_at, :finished_at)
    end

    def require_admin
      unless current_user.admin?
            flash[:error] = "Unauthorised user"
            redirect_to root_path
          end
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def users_for_project(project)
    user_id_array = project.events.pluck(:user_id)
    User.where(id: user_id_array)
  end

  def total_time_for_project(project)
    project.events.sum(:total_hours)
  end

  def current_month_time_for_project(project)
    date_range = (Date.current.beginning_of_month..Date.current.end_of_month)
    project.events.where(starts_at: date_range).sum(:total_hours)
  end
end

app/views/projects/_form.html.erb
<%= form_for(@project, class: 'form') do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :started_at %><br />
    <%= f.datetime_select :started_at %>
  </div>

  <div class="form-group">
    <%= f.label :finished %><br>
    <%= f.check_box :finished, class: "form-control", id: "finished_checkbox" %>
  </div>

  <div class="form-group" id="finished_group">
    <%= f.label :finished_at %><br />
    <%= f.datetime_select :finished_at %>
  </div>

  <div class="actions">
    <%= f.submit 'Update', class: 'btn btn-default' %>
  </div>
<% end %>

app/views/projects/edit.html.erb
 <div class="col-md-4">
  <h1>Editing project</h1>

  <%= render 'form' %>
  <%= link_to 'Back', projects_path %>
</div>

app/views/projects/index.html.erb
<h1>Projects</h1>

<table class="table">
  <thead>
    <tr>
      <th><%= sortable_column 'Name' %></th>
      <th><%= sortable_column "Started at:", column: "started_at"  %></th>
      <th><%= sortable_column 'Finished' %></th>
      <th><%= sortable_column 'Finished at:', column: "finished_at" %></th>
      <th>Users</th>
      <th>Current / Total</th>
      <th>Actions</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.started_at.to_date %></td>
        <td><%= project.finished? ? 'yes' : 'no' %></td>
        <td><%= project.finished? ? project.finished_at.to_date : 'active' %>
        <td>
          <% users = users_for_project(project)%>
          <% users.each do |user|%>
            <%= link_to user.name, reports_get_path(user) %>;
          <% end %>
        </td>
        <td><%= current_month_time_for_project(project) %>h / <%= total_time_for_project(project) %>h</td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Project', new_project_path, class: 'btn btn-default' %>
<br /> <br />

app/views/projects/new.html.erb
 <div class="col-md-4">
  <h1>New project</h1>

  <%= render 'form' %>
  <%= link_to 'Back', projects_path %>
</div>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>