config/routes.rb
ProjectCalendar::Application.routes.draw do
  resources :projects

  devise_for :users
  scope "/admin" do
    resources :users
  end

  resources :events

  get "calendar/index"
  get "calendar/show"

  get "reports/index"
  get "reports/:user_id", to: 'reports#get', as: 'reports_get'

  root 'calendar#index'
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <%= content_tag :li, msg, :id => "error_#{msg}" if msg.is_a?(String) %>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectCalendar</title>

  <%= javascript_include_tag "jquery.js" %>


  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

  <%= csrf_meta_tags %>
</head>
<body>

<!--  Navigation bar -->
<nav class="navbar navbar-default" role="navigation">

  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Bit by bit", "/", class: "navbar-brand" %>
  </div>

  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li class="<%= 'active' if params[:controller] == 'calendar' %>"><%=link_to "Calendar", calendar_index_path %></li>
      <% if  current_user && current_user.admin? %>
        <li class="<%= 'active' if params[:controller] == 'users' %>"><%=link_to "Users", users_path %></li>
        <li class="<%= 'active' if params[:controller] == 'projects' %>"><%=link_to "Projects", projects_path %></li>
      <% end %>
      <li class="<%= 'active' if params[:controller] == 'reports' %>"><%=link_to "Report", reports_index_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if params[:controller] != 'devise/sessions' && params[:controller] != 'devise/registrations'%>
        <li><%= link_to 'Account', edit_user_path(current_user) %></li>
        <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
      <% end %>
    </ul>
  </div>
</nav>

<!--  Content -->
<div class="container">
   <!-- <li><%= debug params %></li> -->
  <%= yield %>
</div>

<!--  Flash messages -->
<% if params[:controller] != 'devise/sessions' && params[:controller] != 'devise/registrations'%>
  <% flash.each do |key, value| %>
        <div class="<%= flash_class(key) %>">
              <%= value %>
        </div>
  <% end %>
<% end %>

</body>
</html>